### ISSUE TITLE
About that license.

### ISSUE THREAD

**Issue by Jaykul** [mavaddat/wasp#12]
So, I don't mind that you took my code ... 
At least you left all the copyright headers 😉

I don't really even care that you did not even mention me (apart from leaving those copyright headers) ...
But I feel like changing the license (which was MS-RL) to MPL is a little weird.

Do you want to just change it to MIT?

**Comment by mavaddat** [comment]
> So, I don't mind that you took my code ... At least you left all the copyright headers 😉

I was trying to mirror your project on GitHub back when I did not know much about GitHub. I also did not spend the time to add all the details. I think I did not see you on GitHub when I first mirrored it here. I am sorry I did not put your name on the `README.md`.

I added you as a collaborator so I can pass ownership to you. So far, I compiled the project locally, updated the project artifacts, updated the logo, otherwise it remains the same, I think.

> I don't really even care that you did not even mention me (apart from leaving those copyright headers) ... But I feel like changing the license (which was MS-RL) to MPL is a little weird.

IIRC, I could not see the license when I mirrored the project originally, so I tried to figure out the implied license. I see now that the `.cs` files indicate MS-RL. I can

> Do you want to just change it to MIT?

Sure.
